<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(FiveMCleanerWindowsTargetFramework)</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <ProjectReference Include="..\FiveMCleaner.Contracts\FiveMCleaner.Contracts.csproj" />
  </ItemGroup>
</Project>
