using System.Collections.ObjectModel;
using FiveMCleaner.Contracts;

namespace FiveMCleaner.Core.Catalog;

public sealed class ActionCatalog
{
    public const int CurrentVersion = 7;

    private static readonly string[] NoPrerequisites = [];
    private static readonly string[] RequiresFiveMStoppedFirst = [OptimizationActionIds.VerifyFiveMIsStopped];
    private static readonly string[] RequiresGtaVStoppedFirst = [OptimizationActionIds.VerifyGtaVIsStopped];

    private static readonly OptimizationProfile[] AllProfiles =
    [
        OptimizationProfile.Light,
        OptimizationProfile.Balanced,
        OptimizationProfile.Aggressive
    ];

    private static readonly OptimizationProfile[] BalancedAndAggressive =
    [
        OptimizationProfile.Balanced,
        OptimizationProfile.Aggressive
    ];

    private readonly IReadOnlyDictionary<string, OptimizationActionDefinition> _byId;

    private ActionCatalog(IReadOnlyList<OptimizationActionDefinition> actions)
    {
        Actions = new ReadOnlyCollection<OptimizationActionDefinition>(actions.ToArray());
        _byId = new ReadOnlyDictionary<string, OptimizationActionDefinition>(
            actions.ToDictionary(action => action.Id, StringComparer.Ordinal));
    }

    public static ActionCatalog Current { get; } = new(CreateActions());

    public IReadOnlyList<OptimizationActionDefinition> Actions { get; }

    public bool TryGet(string actionId, out OptimizationActionDefinition? definition)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(actionId);
        return _byId.TryGetValue(actionId, out definition);
    }

    public OptimizationActionDefinition GetRequired(string actionId)
    {
        return TryGet(actionId, out var definition)
            ? definition!
            : throw new KeyNotFoundException($"Unknown optimization action ID '{actionId}'.");
    }

    private static IReadOnlyList<OptimizationActionDefinition> CreateActions()
    {
        return
        [
            Define(
                OptimizationActionIds.VerifyFiveMIsStopped,
                "Verificar estado do FiveM",
                "Confirma que os processos do FiveM estão encerrados antes de qualquer alteração em cache ou gráficos.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Protege a integridade dos arquivos do FiveM.",
                ActionOptionGate.Always,
                isCritical: true,
                detectionSummary: "Inspeciona os processos ativos cuja imagem pertence à pasta do FiveM.",
                confirmationSummary: "A verificação passa quando nenhum processo do FiveM está em execução.",
                undoSummary: "Somente leitura: não há nada para desfazer.",
                riskLimitations: "Se o FiveM estiver aberto, as ações dependentes são ignoradas com segurança."),
            Define(
                OptimizationActionIds.VerifyGtaVIsStopped,
                "Verificar estado do GTA V",
                "Confirma que o GTA V Legacy está fechado antes de qualquer alteração no settings.xml dele.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Evita uma execução parcial quando a otimização do GTA V está habilitada.",
                ActionOptionGate.ApplyGtaVGraphicsPreset,
                isCritical: true,
                detectionSummary: "Inspeciona os processos ativos cuja imagem pertence à pasta do GTA V.",
                confirmationSummary: "A verificação passa quando o GTA V não está em execução.",
                undoSummary: "Somente leitura: não há nada para desfazer.",
                riskLimitations: "Se o GTA V estiver aberto, os ajustes gráficos do GTA V são ignorados com segurança."),
            Define(
                OptimizationActionIds.DiagnoseBottleneck,
                "Diagnosticar gargalo provável",
                "Analisa memória disponível, processadores lógicos e espaço livre em disco para apontar o recurso mais limitante, sem alterar nada.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 3,
                expectedImpact: "Ajuda a entender onde o computador está limitado; não mede FPS nem promete ganho.",
                ActionOptionGate.Always,
                detectionSummary: "Lê memória total/disponível, contagem de processadores lógicos e espaço livre no disco do sistema.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não há nada para desfazer.",
                riskLimitations: "É uma heurística local, não um benchmark; resultados variam conforme a carga no momento da leitura."),
            Define(
                OptimizationActionIds.DetectOverlaysAndCaptureSoftware,
                "Detectar overlays e captura em segundo plano",
                "Verifica a presença de overlays e softwares de captura de terceiros conhecidos (NVIDIA, RTSS, Discord, Xbox Game Bar) em execução, sem fechá-los.",
                ActionCategory.WindowsGaming,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 3,
                expectedImpact: "Informa quais overlays conhecidos estão ativos para você decidir se quer fechá-los manualmente.",
                ActionOptionGate.Always,
                detectionSummary: "Compara os processos em execução com uma lista pequena e conhecida de overlays/capturadores.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não fecha nem altera nenhum processo.",
                riskLimitations: "Detecção heurística por nome de processo; presença não significa necessariamente problema."),
            Define(
                OptimizationActionIds.ReadFiveMLegacyLogs,
                "Ler log recente do FiveM",
                "Localiza o log mais recente do FiveM Legacy e resume sua idade e ocorrências de possíveis erros, sem modificar nada.",
                ActionCategory.Storage,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 3,
                expectedImpact: "Dá um sinal rápido de problemas recentes sem precisar abrir o arquivo manualmente.",
                ActionOptionGate.Always,
                detectionSummary: "Abre o log mais recente da pasta logs do FiveM com acesso compartilhado, mesmo com o FiveM aberto.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não altera nem remove nenhum log.",
                riskLimitations: "Contagem de possíveis erros é aproximada (busca textual); não substitui um diagnóstico completo."),
            Define(
                OptimizationActionIds.GuidePerformanceDiagnostics,
                "Orientar diagnóstico de desempenho",
                "Aponta os comandos oficiais do FiveM (cl_drawfps, cl_drawperf, netgraph) para medir FPS e rede dentro do próprio jogo.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Ensina a medir o desempenho real usando ferramentas oficiais, sem prometer um número específico.",
                ActionOptionGate.Always,
                detectionSummary: "Não lê nada do sistema; apresenta uma orientação fixa baseada na documentação oficial do FiveM.",
                confirmationSummary: "Sempre é concluída com a mensagem de orientação.",
                undoSummary: "Somente leitura: não há nada para desfazer.",
                riskLimitations: "Não injeta overlay nem mede FPS pelo aplicativo; a medição é feita pelo próprio FiveM."),
            Define(
                OptimizationActionIds.DiagnoseNetworkHealth,
                "Diagnosticar saúde da rede local",
                "Lê contadores de pacotes descartados e com erro das placas de rede ativas, sem enviar tráfego a nenhum servidor.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 3,
                expectedImpact: "Indica sinais locais de instabilidade de rede; não mede ping nem jitter até o servidor do FiveM.",
                ActionOptionGate.Always,
                detectionSummary: "Lê estatísticas já coletadas pelo Windows para as placas de rede ativas (pacotes descartados/com erro).",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não envia nem recebe tráfego de rede.",
                riskLimitations: "Não substitui netgraph/cl_drawperf do próprio FiveM para latência real até o servidor."),
            Define(
                OptimizationActionIds.DiagnoseThermalThrottling,
                "Diagnosticar temperatura e throttling",
                "Tenta ler a zona térmica ACPI exposta pelo Windows; a maioria das placas-mãe não expõe esse dado sem software do fabricante, e isso é informado com honestidade.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Quando disponível, ajuda a identificar quedas de desempenho por superaquecimento.",
                ActionOptionGate.Always,
                detectionSummary: "Consulta MSAcpi_ThermalZoneTemperature (WMI) e valida se o valor está numa faixa plausível.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não há nada para desfazer.",
                riskLimitations: "Sem software do fabricante da placa-mãe/GPU, a maioria dos sistemas não expõe essa leitura; o app nunca inventa um valor."),
            Define(
                OptimizationActionIds.DiagnosePagefileCommit,
                "Diagnosticar pagefile e memória committed",
                "Lê o tamanho total e disponível do arquivo de paginação para avisar quando o sistema está perto do limite de commit, sem redimensionar nada.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Sinaliza risco de lentidão por paginação excessiva antes que ele afete a sessão.",
                ActionOptionGate.Always,
                detectionSummary: "Lê o total e o disponível do arquivo de paginação do Windows (GlobalMemoryStatusEx).",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: nunca redimensiona ou desativa o pagefile.",
                riskLimitations: "O Windows já gerencia o pagefile automaticamente na maioria dos sistemas; o app não altera esse gerenciamento."),
            Define(
                OptimizationActionIds.DiagnoseCacheIntegrity,
                "Diagnosticar integridade do índice de cache",
                "Verifica se o índice de cache do FiveM (content_index.xml) existe e está bem formado, recomendando o reparo já existente quando necessário.",
                ActionCategory.Storage,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 3,
                expectedImpact: "Ajuda a decidir quando vale a pena reparar o cache em vez de investigar outra causa.",
                ActionOptionGate.Always,
                detectionSummary: "Tenta abrir e interpretar como XML o content_index.xml de server-cache e server-cache-priv, se existirem.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não repara nem apaga nada; apenas recomenda a ação de reparo de cache já existente.",
                riskLimitations: "A ausência do arquivo não é tratada como corrupção; apenas um arquivo presente e ilegível gera aviso."),
            Define(
                OptimizationActionIds.DetectGpuVendor,
                "Detectar fabricante da GPU",
                "Identifica o fabricante (NVIDIA, AMD ou Intel) das GPUs detectadas e orienta o ajuste manual no painel oficial do fabricante, sem escrever nenhum perfil de driver.",
                ActionCategory.WindowsGaming,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Facilita encontrar o painel de controle correto sem o app tocar em perfis de driver.",
                ActionOptionGate.Always,
                detectionSummary: "Lê a descrição do driver de vídeo já usada no diagnóstico de hardware do aplicativo.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não abre, escreve nem reseta nenhum perfil NVIDIA/AMD/Intel.",
                riskLimitations: "Não sobrescreve perfil de GPU nem força shader cache; isso é proibido pelo modelo de segurança do produto."),
            Define(
                OptimizationActionIds.DiagnoseCpuDetails,
                "Diagnosticar núcleos, threads e frequência da CPU",
                "Lê a quantidade de núcleos físicos, threads lógicas e a frequência atual/máxima da CPU via WMI padrão.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Ajuda a entender a capacidade de CPU disponível e sinais de queda de frequência.",
                ActionOptionGate.Always,
                detectionSummary: "Consulta Win32_Processor (WMI) por núcleos, threads e clock atual/máximo.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não altera afinidade, prioridade nem frequência.",
                riskLimitations: "Não lê temperatura nem sensores por núcleo; isso exigiria driver de terceiros, fora do escopo do produto."),
            Define(
                OptimizationActionIds.DiagnoseGpuDetails,
                "Diagnosticar VRAM e tipo da GPU",
                "Lê a VRAM reportada pelo driver e estima se cada GPU detectada é integrada ou dedicada, sem escrever nenhum perfil.",
                ActionCategory.WindowsGaming,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Ajuda a identificar se o FiveM está usando a GPU dedicada e se há VRAM suficiente.",
                ActionOptionGate.Always,
                detectionSummary: "Lê HardwareInformation.qwMemorySize e a descrição do driver no registro de vídeo já usado pelo app.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não escreve nenhum valor de registro ou perfil de driver.",
                riskLimitations: "A classificação integrada/dedicada é uma estimativa por nome do driver, não uma leitura de hardware garantida."),
            Define(
                OptimizationActionIds.DiagnoseRamDetails,
                "Diagnosticar frequência, canais e XMP/EXPO da RAM",
                "Lê a frequência configurada e nominal de cada módulo de RAM, estimando single-channel e se XMP/EXPO parece desativado.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Ajuda a identificar memória rodando abaixo do potencial nominal.",
                ActionOptionGate.Always,
                detectionSummary: "Consulta Win32_PhysicalMemory (WMI) por capacidade, ConfiguredClockSpeed e Speed de cada módulo.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não altera BIOS, perfil de memória nem frequência.",
                riskLimitations: "Canal e XMP/EXPO são estimativas heurísticas; a confirmação exata depende da BIOS/UEFI."),
            Define(
                OptimizationActionIds.DiagnoseStorageHealth,
                "Diagnosticar tipo e saúde das unidades",
                "Identifica HDD, SSD ou NVMe de cada unidade física e lê o status de saúde preditiva (SMART/NVMe Health), sem reparar nada.",
                ActionCategory.Storage,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Alerta cedo sobre discos com risco de falha ou tipo inadequado para o FiveM.",
                ActionOptionGate.Always,
                detectionSummary: "Consulta MSFT_PhysicalDisk (Storage Management API), que cobre SATA S.M.A.R.T. e NVMe Health sem driver adicional.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não repara, formata nem move dados.",
                riskLimitations: "Reporta todas as unidades físicas detectadas; não afirma com certeza qual delas hospeda o FiveM."),
            Define(
                OptimizationActionIds.DiagnoseDriverVersions,
                "Diagnosticar build do Windows e versões de driver",
                "Lê o build exato do Windows e as versões dos drivers de vídeo, rede, áudio e chipset (quando identificável).",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Ajuda a identificar drivers desatualizados como causa de instabilidade.",
                ActionOptionGate.Always,
                detectionSummary: "Consulta Win32_PnPSignedDriver (WMI) agrupado por classe de dispositivo, mais Environment.OSVersion para o build.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não instala, atualiza nem reverte nenhum driver.",
                riskLimitations: "O driver de chipset é identificado por heurística de nome; nem todo fabricante o expõe como classe própria."),
            Define(
                OptimizationActionIds.DiagnoseDisplayConfiguration,
                "Diagnosticar resolução, taxa de atualização e HAGS",
                "Compara a taxa de atualização configurada com a máxima suportada na resolução atual e lê o estado do HAGS.",
                ActionCategory.WindowsGaming,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Evita que o monitor fique configurado abaixo da taxa de atualização que suporta.",
                ActionOptionGate.Always,
                detectionSummary: "Usa EnumDisplaySettings (Win32) para o modo atual/máximo e o registro de GraphicsDrivers para HwSchMode.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não altera resolução, taxa de atualização nem HAGS.",
                riskLimitations: "G-SYNC/FreeSync/VRR não têm API pública sem driver do fabricante; o app informa isso em vez de adivinhar."),
            Define(
                OptimizationActionIds.DiagnoseSessionSettings,
                "Diagnosticar Modo de Jogo, tela cheia e plano de energia",
                "Lê o estado atual do Modo de Jogo, das otimizações para tela cheia e do plano de energia ativo, sem alterar nada.",
                ActionCategory.WindowsGaming,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Mostra o estado real antes de decidir se vale a pena aplicar as ações correspondentes.",
                ActionOptionGate.Always,
                detectionSummary: "Lê os mesmos valores de registro usados pelas ações de Modo de Jogo/captura, mais o esquema de energia ativo.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não ativa nem desativa nada.",
                riskLimitations: "Apenas relata o estado atual; para aplicar mudanças, use as ações correspondentes do perfil."),
            Define(
                OptimizationActionIds.DiagnoseThrottlingSignal,
                "Diagnosticar sinais combinados de throttling",
                "Combina queda de frequência sob carga, eventos de erro de hardware (WHEA) e temperatura disponível para indicar 'possível throttling', sem sensor direto por núcleo.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 3,
                expectedImpact: "Sinaliza possível throttling mesmo quando não há sensor de temperatura confiável disponível.",
                ActionOptionGate.Always,
                detectionSummary: "Combina Win32_Processor (clock), uma amostra de uso de CPU, eventos Kernel-WHEA recentes e a zona térmica ACPI, quando disponível.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não altera plano de energia, afinidade nem prioridade.",
                riskLimitations: "Sem sensor direto por núcleo, o resultado é sempre apresentado como 'possível', nunca como certeza."),
            Define(
                OptimizationActionIds.DiagnoseResourceUsage,
                "Diagnosticar uso atual de CPU, disco, GPU e rede",
                "Faz uma leitura instantânea (não uma média) do uso de CPU, disco, GPU (quando disponível) e throughput de rede.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 3,
                expectedImpact: "Dá contexto imediato de carga do sistema no momento da otimização.",
                ActionOptionGate.Always,
                detectionSummary: "Usa PerformanceCounter para CPU/disco/GPU (categoria nativa 'GPU Engine') e contadores de interface de rede para throughput.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não define prioridade nem afinidade de processos.",
                riskLimitations: "É uma amostra curta (~300 ms), não uma média sustentada; a GPU pode não estar disponível em todo hardware."),
            Define(
                OptimizationActionIds.DiagnosePciLink,
                "Diagnosticar link PCIe da GPU",
                "Tenta ler a largura e velocidade atual/máxima do link PCIe de cada GPU via propriedades de dispositivo do Windows, sem driver de terceiros.",
                ActionCategory.WindowsGaming,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Ajuda a identificar uma GPU rodando num slot ou modo PCIe mais lento que o esperado.",
                ActionOptionGate.Always,
                detectionSummary: "Usa CM_Get_DevNode_Property (cfgmgr32) com os DEVPKEYs padrão de link PCIe do Windows.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não reconfigura o barramento nem o slot.",
                riskLimitations: "Nem todo driver/placa-mãe expõe essas propriedades; quando ausente, o app informa isso em vez de adivinhar."),
            Define(
                OptimizationActionIds.DiagnoseHardwareStability,
                "Diagnosticar idade da BIOS e estabilidade de hardware",
                "Lê a data de lançamento da BIOS e eventos recentes de erro de hardware (WHEA) no Log de Eventos do Windows.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Ajuda a identificar BIOS desatualizada ou instabilidade de hardware como causa raiz.",
                ActionOptionGate.Always,
                detectionSummary: "Consulta Win32_BIOS (WMI) e eventos da fonte Microsoft-Windows-Kernel-WHEA no log System.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não atualiza BIOS nem limpa o log de eventos.",
                riskLimitations: "Resizable BAR/Above 4G/Smart Access Memory não são detectáveis de forma confiável sem ferramenta do fabricante; o app informa essa limitação em vez de adivinhar."),
            Define(
                OptimizationActionIds.ClassifyBottleneck,
                "Classificar tipo provável de gargalo",
                "Combina uso de CPU/GPU/disco/rede, memória, temperatura e o processo que mais consome CPU para apontar o recurso mais provavelmente limitante no momento.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 3,
                expectedImpact: "Ajuda a decidir qual ajuste vale mais a pena antes de tentar várias mudanças às cegas.",
                ActionOptionGate.Always,
                detectionSummary: "Combina as leituras já feitas por outros diagnósticos (uso de recursos, temperatura, rede, memória) com o processo de maior uso de CPU no momento (Win32_PerfFormattedData_PerfProc_Process).",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não encerra nem prioriza nenhum processo.",
                riskLimitations: "É uma classificação por eliminação a partir de sinais locais; 'servidor limitado' é a conclusão quando nenhum sinal local se destaca, não uma medição direta do servidor."),
            Define(
                OptimizationActionIds.CleanUserTemporaryFiles,
                "Limpar temporários antigos",
                "Remove somente arquivos temporários do usuário que ultrapassaram o período de retenção configurado.",
                ActionCategory.Storage,
                ActionRisk.Low,
                ActionReversibility.Irreversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 18,
                expectedImpact: "Libera espaço; não promete aumento direto de FPS.",
                ActionOptionGate.CleanUserTemporaryFiles,
                detectionSummary: "Percorre a pasta Temp do usuário buscando arquivos além do período de retenção.",
                confirmationSummary: "Confirma que os arquivos antigos selecionados não existem mais após a limpeza.",
                undoSummary: "Irreversível: arquivos temporários antigos não são preservados em quarentena.",
                riskLimitations: "Remove apenas arquivos antigos do próprio usuário; nunca toca em pastas do sistema."),
            Define(
                OptimizationActionIds.PruneLegacyCrashDumps,
                "Remover diagnósticos antigos",
                "Remove dumps e logs antigos do FiveM Legacy, preservando os arquivos dentro do período de retenção.",
                ActionCategory.Storage,
                ActionRisk.Low,
                ActionReversibility.Irreversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: true,
                progressWeight: 12,
                expectedImpact: "Libera espaço ocupado por diagnósticos antigos.",
                ActionOptionGate.RemoveOldFiveMCrashDumps,
                prerequisites: RequiresFiveMStoppedFirst,
                detectionSummary: "Lista dumps e logs do FiveM mais antigos que o período de retenção.",
                confirmationSummary: "Confirma que os diagnósticos antigos foram removidos e os recentes preservados.",
                undoSummary: "Irreversível: diagnósticos antigos não são copiados para o journal.",
                riskLimitations: "Dumps podem ser úteis para suporte; apenas os fora do período de retenção são removidos."),
            Define(
                OptimizationActionIds.RepairLegacyServerCache,
                "Reparar cache de servidores",
                "Remove somente caches regeneráveis de conteúdo de servidores do FiveM Legacy.",
                ActionCategory.Storage,
                ActionRisk.Moderate,
                ActionReversibility.RebuildableData,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: true,
                progressWeight: 30,
                expectedImpact: "Pode corrigir corrupção ou liberar espaço; o primeiro carregamento ficará mais lento.",
                ActionOptionGate.RepairLegacyServerCache,
                prerequisites: RequiresFiveMStoppedFirst,
                detectionSummary: "Mede o tamanho de server-cache e server-cache-priv sob a instalação do FiveM.",
                confirmationSummary: "Confirma que apenas os caches regeneráveis foram removidos.",
                undoSummary: "Dados regeneráveis: o FiveM baixa o conteúdo novamente no próximo acesso ao servidor.",
                riskLimitations: "O primeiro carregamento fica mais lento; clipes antigos do Rockstar Editor podem deixar de funcionar."),
            Define(
                OptimizationActionIds.EnableGameMode,
                "Ativar Modo de Jogo",
                "Ativa o recurso de jogos do Windows para priorização quando jogos estão em execução.",
                ActionCategory.WindowsGaming,
                ActionRisk.Low,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 5,
                expectedImpact: "Pode melhorar a consistência da sessão em sistemas compatíveis.",
                ActionOptionGate.EnableGameMode,
                detectionSummary: "Lê o valor AutoGameModeEnabled do registro do usuário atual.",
                confirmationSummary: "Confirma que o Modo de Jogo ficou habilitado após a gravação.",
                undoSummary: "Totalmente reversível: o valor anterior do registro é restaurado no rollback.",
                riskLimitations: "O ganho depende do hardware e da versão do Windows; pode não ter efeito perceptível."),
            Define(
                OptimizationActionIds.PreferHighPerformanceGpu,
                "Preferir GPU de alto desempenho",
                "Define a preferência gráfica do Windows para o launcher e os renderizadores detectados do FiveM Legacy.",
                ActionCategory.WindowsGaming,
                ActionRisk.Low,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: true,
                progressWeight: 5,
                expectedImpact: "Evita o uso acidental da GPU econômica em computadores com múltiplas GPUs.",
                ActionOptionGate.PreferHighPerformanceGpu,
                prerequisites: RequiresFiveMStoppedFirst,
                detectionSummary: "Lê a preferência gráfica registrada para o executável do FiveM.",
                confirmationSummary: "Confirma que a preferência de alto desempenho ficou registrada.",
                undoSummary: "Totalmente reversível: a preferência anterior é restaurada no rollback.",
                riskLimitations: "Só faz diferença em computadores com mais de uma GPU."),
            Define(
                OptimizationActionIds.DisableBackgroundCapture,
                "Desativar captura em segundo plano",
                "Desativa a gravação contínua em segundo plano do Windows sem remover o Game Bar.",
                ActionCategory.WindowsGaming,
                ActionRisk.Low,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                BalancedAndAggressive,
                requiresFiveMStopped: false,
                progressWeight: 4,
                expectedImpact: "Reduz atividade de captura quando ela estava habilitada.",
                ActionOptionGate.DisableBackgroundCapture,
                detectionSummary: "Lê o valor de gravação em segundo plano (Game DVR) do registro do usuário.",
                confirmationSummary: "Confirma que a captura em segundo plano ficou desabilitada.",
                undoSummary: "Totalmente reversível: o valor anterior é restaurado no rollback.",
                riskLimitations: "Não remove o Game Bar nem afeta gravações manuais que você iniciar."),
            Define(
                OptimizationActionIds.EnableSessionPerformancePowerPlan,
                "Ativar plano de energia de alto desempenho",
                "Ativa um plano de energia de desempenho na tomada e registra o estado anterior para rollback.",
                ActionCategory.Power,
                ActionRisk.Moderate,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.Administrator,
                BalancedAndAggressive,
                requiresFiveMStopped: false,
                progressWeight: 7,
                expectedImpact: "Reduz limitação de energia; aumenta consumo e temperatura até o rollback.",
                ActionOptionGate.UseSessionPerformancePowerPlan,
                requiresAcPower: true,
                detectionSummary: "Lê o plano de energia ativo e verifica se o computador está na tomada.",
                confirmationSummary: "Confirma que o plano de desempenho ficou ativo.",
                undoSummary: "Totalmente reversível: o plano anterior é restaurado no rollback.",
                riskLimitations: "Só é aplicado na tomada; aumenta consumo e temperatura enquanto ativo."),
            Define(
                OptimizationActionIds.ApplyLightLegacyGraphics,
                "Ajustar gráficos leves do FiveM",
                "Desliga apenas antialiasing de maior custo no arquivo existente do FiveM, com backup.",
                ActionCategory.FiveMGraphics,
                ActionRisk.Low,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                [OptimizationProfile.Light],
                requiresFiveMStopped: true,
                progressWeight: 7,
                expectedImpact: "Remove custos altos preservando texturas, resolução e a maior parte da qualidade visual.",
                ActionOptionGate.ApplyLegacyGraphicsPreset,
                prerequisites: RequiresFiveMStoppedFirst,
                detectionSummary: "Lê as opções existentes de gta5_settings.xml do FiveM.",
                confirmationSummary: "Confirma que apenas as opções caras foram ajustadas e o arquivo permanece válido.",
                undoSummary: "Totalmente reversível: o backup do arquivo é restaurado no rollback.",
                riskLimitations: "Só altera opções já presentes; não distribui um XML genérico."),
            Define(
                OptimizationActionIds.ApplyBalancedLegacyGraphics,
                "Aplicar gráficos equilibrados",
                "Ajusta somente opções existentes do arquivo gráfico do FiveM Legacy e cria backup antes da gravação.",
                ActionCategory.FiveMGraphics,
                ActionRisk.Moderate,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                [OptimizationProfile.Balanced],
                requiresFiveMStopped: true,
                progressWeight: 12,
                expectedImpact: "Equilibra qualidade visual, uso de GPU e estabilidade de quadros.",
                ActionOptionGate.ApplyLegacyGraphicsPreset,
                prerequisites: RequiresFiveMStoppedFirst,
                detectionSummary: "Lê as opções existentes de gta5_settings.xml do FiveM.",
                confirmationSummary: "Confirma que os limites equilibrados foram aplicados e o arquivo permanece válido.",
                undoSummary: "Totalmente reversível: o backup do arquivo é restaurado no rollback.",
                riskLimitations: "Resultados variam conforme o hardware; só altera opções já presentes."),
            Define(
                OptimizationActionIds.ApplyAggressiveLegacyGraphics,
                "Aplicar gráficos agressivos",
                "Reduz opções gráficas de maior custo no FiveM Legacy e cria backup antes da gravação.",
                ActionCategory.FiveMGraphics,
                ActionRisk.High,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                [OptimizationProfile.Aggressive],
                requiresFiveMStopped: true,
                progressWeight: 14,
                expectedImpact: "Prioriza FPS e responsividade em vez de qualidade visual.",
                ActionOptionGate.ApplyLegacyGraphicsPreset,
                prerequisites: RequiresFiveMStoppedFirst,
                detectionSummary: "Lê as opções existentes de gta5_settings.xml do FiveM.",
                confirmationSummary: "Confirma que as opções pesadas foram reduzidas e o arquivo permanece válido.",
                undoSummary: "Totalmente reversível: o backup do arquivo é restaurado no rollback.",
                riskLimitations: "Reduz qualidade visual de forma perceptível; não força resolução mínima."),
            Define(
                OptimizationActionIds.ApplyLightGtaVGraphics,
                "Ajustar gráficos leves do GTA V",
                "Detecta o settings.xml do GTA V Legacy, reduz somente opções caras já existentes e cria backup.",
                ActionCategory.FiveMGraphics,
                ActionRisk.Low,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                [OptimizationProfile.Light],
                requiresFiveMStopped: true,
                progressWeight: 7,
                expectedImpact: "Preserva resolução e qualidade geral enquanto reduz antialiasing caro.",
                ActionOptionGate.ApplyGtaVGraphicsPreset,
                prerequisites: RequiresGtaVStoppedFirst,
                detectionSummary: "Lê as opções existentes do settings.xml do GTA V Legacy.",
                confirmationSummary: "Confirma que apenas as opções caras foram ajustadas e o arquivo permanece válido.",
                undoSummary: "Totalmente reversível: o backup do arquivo é restaurado no rollback.",
                riskLimitations: "Só altera opções já presentes; não altera resolução, tela ou adaptador."),
            Define(
                OptimizationActionIds.ApplyBalancedGtaVGraphics,
                "Equilibrar gráficos do GTA V",
                "Aplica limites equilibrados somente em opções existentes do settings.xml do GTA V Legacy, com backup.",
                ActionCategory.FiveMGraphics,
                ActionRisk.Moderate,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                [OptimizationProfile.Balanced],
                requiresFiveMStopped: true,
                progressWeight: 11,
                expectedImpact: "Equilibra qualidade, uso de GPU e estabilidade de quadros também no GTA V base.",
                ActionOptionGate.ApplyGtaVGraphicsPreset,
                prerequisites: RequiresGtaVStoppedFirst,
                detectionSummary: "Lê as opções existentes do settings.xml do GTA V Legacy.",
                confirmationSummary: "Confirma que os limites equilibrados foram aplicados e o arquivo permanece válido.",
                undoSummary: "Totalmente reversível: o backup do arquivo é restaurado no rollback.",
                riskLimitations: "Resultados variam conforme o hardware; só altera opções já presentes."),
            Define(
                OptimizationActionIds.ApplyAggressiveGtaVGraphics,
                "Priorizar FPS no GTA V",
                "Reduz opções gráficas pesadas do settings.xml do GTA V Legacy sem alterar resolução, tela ou adaptador.",
                ActionCategory.FiveMGraphics,
                ActionRisk.High,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                [OptimizationProfile.Aggressive],
                requiresFiveMStopped: true,
                progressWeight: 13,
                expectedImpact: "Prioriza FPS sem forçar resolução, taxa de atualização, DirectX ou textura mínima.",
                ActionOptionGate.ApplyGtaVGraphicsPreset,
                prerequisites: RequiresGtaVStoppedFirst,
                detectionSummary: "Lê as opções existentes do settings.xml do GTA V Legacy.",
                confirmationSummary: "Confirma que as opções pesadas foram reduzidas e o arquivo permanece válido.",
                undoSummary: "Totalmente reversível: o backup do arquivo é restaurado no rollback.",
                riskLimitations: "Reduz qualidade visual; não força resolução, taxa de atualização ou textura mínima."),
            Define(
                OptimizationActionIds.ReduceWindowsVisualEffects,
                "Reduzir efeitos visuais do Windows",
                "Reduz animações e transparências preservando legibilidade e suavização de fontes.",
                ActionCategory.Appearance,
                ActionRisk.Moderate,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                [OptimizationProfile.Aggressive],
                requiresFiveMStopped: false,
                progressWeight: 6,
                expectedImpact: "Reduz trabalho visual do desktop em computadores limitados.",
                ActionOptionGate.ReduceWindowsVisualEffects,
                detectionSummary: "Lê o estado atual de animações e transparências do Windows.",
                confirmationSummary: "Confirma que os efeitos foram reduzidos preservando a suavização de fontes.",
                undoSummary: "Totalmente reversível: o estado anterior dos efeitos é restaurado no rollback.",
                riskLimitations: "Muda a aparência do desktop; preserva legibilidade e suavização de fontes.")
        ];
    }

    private static OptimizationActionDefinition Define(
        string id,
        string name,
        string description,
        ActionCategory category,
        ActionRisk risk,
        ActionReversibility reversibility,
        RequiredPrivilege requiredPrivilege,
        IReadOnlyList<OptimizationProfile> supportedProfiles,
        bool requiresFiveMStopped,
        int progressWeight,
        string expectedImpact,
        ActionOptionGate optionGate,
        bool requiresAcPower = false,
        bool requiresRestart = false,
        IReadOnlyList<string>? prerequisites = null,
        bool isCritical = false,
        SupportedWindowsVersions supportedWindows = SupportedWindowsVersions.All,
        string detectionSummary = "",
        string confirmationSummary = "",
        string undoSummary = "",
        string riskLimitations = "")
    {
        return new OptimizationActionDefinition(
            id,
            version: 1,
            name,
            description,
            category,
            risk,
            reversibility,
            requiredPrivilege,
            supportedProfiles.ToArray(),
            requiresFiveMStopped,
            requiresAcPower,
            requiresRestart,
            progressWeight,
            expectedImpact,
            optionGate,
            prerequisites ?? NoPrerequisites,
            isCritical,
            supportedWindows,
            detectionSummary,
            confirmationSummary,
            undoSummary,
            riskLimitations);
    }
}
