<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(FiveMCleanerWindowsTargetFramework)</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>FiveMCleaner.ReleaseTool</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../FiveMCleaner.UpdateRuntime/FiveMCleaner.UpdateRuntime.csproj" />
  </ItemGroup>
</Project>
