<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(FiveMCleanerWindowsTargetFramework)</TargetFramework>
    <RootNamespace>FiveMCleaner.Windows</RootNamespace>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Management" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" />
    <ProjectReference Include="../FiveMCleaner.Contracts/FiveMCleaner.Contracts.csproj" />
    <ProjectReference Include="../FiveMCleaner.Core/FiveMCleaner.Core.csproj" />
  </ItemGroup>
</Project>
